# Praktikum 1 

# Introduction to Machine Learning

### Numpys

#### NumPy Indexing and Selection

Mengambil elemen atau sekelompok elemen dari sebuah array

In [1]:
import numpy as np

In [2]:
#membuat array contoh 
arr = np.arange(0,11)

In [3]:
#menampilkan array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#mengambil sebuah nilai berdasarkan indeks
arr[8]

8

In [5]:
#mengambil sebuah nilai di rentang indeks tertentu
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
#mengubah nilai di rentang indeks (Broadcasting)
arr[0:5]=100

#menunjukkan array
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [8]:
# mengembalikan nilai array
arr = np.arange(0,11)

#menunjukkan array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
#memotong array
slice_of_arr = arr[0:6]

#menunjukkan potongan
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [10]:
#mengubah potongan
slice_of_arr[:]=99

#menunjukkan potongan lagi
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [11]:
#array aslinya juga berubah
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [12]:
#untuk mendapatkan salinan agar array asli tidak berubah, ada perintah eksplisit
arr_salinan = arr.copy()

arr_salinan

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

##### Array 2D

Formatnya arr_2d[baris][kolom] atau arr_2d[baris,kolom]

In [13]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [14]:
#indeks baris
arr_2d[1]

array([20, 25, 30])

In [15]:
#elemen individu
arr_2d[1][0]

20

In [16]:
arr_2d[1,0]

20

In [17]:
#mengambil beberapa elemen dalam rentang indeks tertentu
arr_2d[:2,1:2]

array([[10],
       [25]])

In [18]:
#mengambil baris paling akhir
arr_2d[2]

array([35, 40, 45])

In [19]:
#cara lain untuk mengambil baris paling akhir

arr_2d[2,:]

array([35, 40, 45])

In [20]:
arr_2d[:,1:2]

array([[10],
       [25],
       [40]])

In [21]:
arr_2d[:,1]

array([10, 25, 40])

##### Mengambil Baris/Kolom tanpa berurutan

In [22]:
#set array kosong
arr2d = np.zeros((10,8))

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
#array berisi angka 1
arr2da = np.ones((10,8))

arr2da

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [24]:
arr2d.shape[0]

10

In [25]:
arr2d.shape[1]

8

In [26]:
#panjang array
arr_length = arr2d.shape[1]

In [27]:
#mengisi array dengan value 0-9

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
#mengambil baris ke 3, 5, 7, dan 9

arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
#urutannya bisa dibolak-balik
arr2d[[7,1,5,2]]

array([[7., 7., 7., 7., 7., 7., 7., 7.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [5., 5., 5., 5., 5., 5., 5., 5.],
       [2., 2., 2., 2., 2., 2., 2., 2.]])

##### Mengambil Array berdasarkan Operasi Boolean

In [30]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [32]:
arr > 7

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [33]:
bool_arr = arr>4


In [34]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [35]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [36]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
x = 2
arr[arr>x]

array([3, 4, 5, 6, 7, 8, 9])

#### Menyusun Array Random 


#### rand 

membuat array dengan bentuk yang diinginkan dan mengisinya dengan sampel acak dari distribusi seragam antara (0,1)

In [61]:
np.random.rand(2)

array([0.44576814, 0.02293449])

In [60]:
np.random.rand(5,5)

array([[0.77875847, 0.10321194, 0.3285958 , 0.24408174, 0.72816718],
       [0.01349996, 0.93788924, 0.13540786, 0.35255174, 0.02686569],
       [0.89120605, 0.80591987, 0.01733213, 0.27217056, 0.38505329],
       [0.24574313, 0.54450814, 0.96049503, 0.06849521, 0.94658214],
       [0.11915353, 0.42612855, 0.31321175, 0.76946456, 0.91309318]])

#### randn

memberikan sampel-sampel dari distribusi normal standar

In [65]:
np.random.randn(2)

array([-0.34584846, -1.29464216])

In [66]:
np.random.randn(5,5)

array([[-0.64019793, -0.05549549, -0.67501153,  1.6597806 ,  0.02920439],
       [-0.679632  ,  0.7783185 , -0.14117996,  0.33314669, -0.47191011],
       [ 1.0690498 ,  0.18356561,  0.29377884,  0.24932139, -0.17038903],
       [ 2.22356876,  0.95169954, -0.43615371,  0.85457166, -1.03041541],
       [-0.15160434,  1.72158825,  0.16745477, -0.35249737, -2.39632577]])

#### randint

memberikan integer acak dari nilai rendah ke tinggi

In [67]:
np.random.randint(1,100)

11

In [68]:
np.random.randint(1,100,10)

array([96, 55, 80, 95, 28, 57, 67,  5, 80, 29])

##### Numpys Operations

###### Aritmatika

In [38]:
arr = np.arange(0,10)

In [39]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [40]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [41]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [42]:
# peringatan karena ada pembagian 0 dengan 0,
# nilai diganti nan
arr/arr

<ipython-input-42-b1e33aeb5b27>:3: RuntimeWarning: invalid value encountered in true_divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [43]:
# peringatan juga, 1/0, jadi tak hingga
1/arr

<ipython-input-43-b2dfd03aec51>:2: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [44]:
arr**3

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

###### Fungsi Array Lainnya

Terdapat banyak [fungsi array umum](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), yang intinya merupakan operasi matematis hanya saja dapat dilakukan pada array. Berikut contohnya:

In [45]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
#mengambil akar kuadrat
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [47]:
#Eksponensial (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [48]:
np.max(arr) #same as arr.max()

9

In [49]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [50]:
np.log(arr)

<ipython-input-50-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [51]:
np.mean(arr)

4.5

In [52]:
np.average(arr)

4.5

In [53]:
np.median(arr)

4.5

In [54]:
np.var(arr)

8.25

In [55]:
np.std(arr)

2.8722813232690143

In [56]:
np.std(arr)*np.std(arr)

8.25